### ISSUE TITLE
Information Classification

### ISSUE THREAD

**Issue by noelmace** [blindnet-io/openness-framework#20]
Define a clear information classification to help include all pieces of information, including closed ones, in the Openness Framework

## Intended outcomes

- All information at blindnet is **Open** by default, except if it fits the potential negative effect listed in **restricted** or **confidential**.
- Every staff member can easily and quickly identify if a new piece of information should be closed or opened.
- DataSec and OpSec requirements for **restricted** and **confidential** levels are well defined and easy to follow.

## Steps

- [x] init a definition of information classification levels (#16)
- [ ] improve this definition with @blindnet-io/engineering 
- [ ] write a DR defining a common document header and classification warning template for all documents (markdown and odt/pdf)
- [ ] define how to store and manage confidential information (in a restricted or open DR?)
- [x] clearly classify Github repositories
- [ ] transfer suitable issues from restricted to open repositories

**Comment by Vuk-BN** [comment]
@noelmace just to clarify so I understand correctly. The third bullet of the intended outcome says that DataSec and OpSec requirements, and I assume code/information, will be private and restricted?

I got a couple of questions from two people recently (one is a government contractor and the other works for a bank, both don't believe in open source in general) on how we plan to manage vulnerabilities in case we build in the open. The best answer I came up with is that the security and data protection code will be restricted and closed. 

So when it comes to data and operational security of the code, if for example a bank wants to adopt it, how do we ensure that:
* Our open source software has no vulnerabilities baked into it, from external contributors 
* Our open source data protection software actually protects the data through out the lifecycle

**Comment by noelmace** [comment]
@blindnet-io/engineering: for step 2 (improve this definition), see @filipblnt's feedback on https://github.com/blindnet-io/openness-framework/pull/16#pullrequestreview-936290882

**Comment by nweldev** [comment]
This issue is sufficiently solved for our current needs.
No DR is required as most of it are still choices we should continue to challenge as we go.

@blindnet-io/engineering can still, if necessary, improve https://github.com/blindnet-io/openness-framework/pull/16
